debug: false

info:
  app: StattAuto Fuhrpark
  author: Hermann Woock
  created: 11.08.2023

server:
  port: 8083
  
spring:
  application:
    name: Fuhrpark
  mvc:
    log-request-details: false
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
  main:
    allow-bean-definition-overriding: true


  
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      show-components: always
      enabled: true 
      probes:
        enabled: true
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
 
logging:
  level:
    root: error
    '[de.woock]': debug